-- Milestone AI, phase 3: stored AI briefs (owner-requested).
-- One table for every AI-written text we keep: the nightly household
-- "morning report" (cat_id null) and per-cat health analysis / vet summary.
-- Storing them makes reading instant — generation happens overnight (cron)
-- or on demand. Safe to run any time; run AFTER 001-004.

create table if not exists ai_briefs (
  id         uuid primary key default gen_random_uuid(),
  kind       text not null,                    -- 'morning_report' | 'health_analysis' | 'vet_summary'
  cat_id     uuid references cats(id),         -- null = household-wide (morning report)
  brief_date date not null,                    -- Jakarta calendar day the brief was made for
  content    text not null,
  model      text,                             -- null = written without AI (e.g. quiet day)
  created_by uuid references app_users(id),    -- null = generated by the nightly cron
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists ai_briefs_lookup
  on ai_briefs (kind, cat_id, created_at desc);

-- Deny-all RLS like every other table: all access is server-side service-role.
alter table ai_briefs enable row level security;
